### ISSUE TITLE
Timezone support (-> Tokyo)

### ISSUE THREAD

**Issue by InBrewJ** [LUSHDigital/lrpi_bootstrap#13]
Display: daylight savings time is NOT shown - e.g. we're still on GMT+0
Things to investigate:

- Can docker not see the host timezone?
- Could also be a problem with the SD image - try and play with the timezone value in settings.json

**Comment by pisuke** [comment]
@bungeejim @InBrewJ @paulharter I've now fixed this in the #15 and [lrpi_display#7](https://github.com/LUSHDigital/lrpi_display/pull/7) pull requests.

**Comment by bungeejim** [comment]
In settings.json. What is the format for specifying the timezones toyko ? do I type >  japan/tokyo
